# server configuration
system:
  appName: ProxyPool
  # service listening address
  httpAddr: 0.0.0.0
  # service listening port
  httpPort: 3000

# mysql
database:
  dbType: mysql
  host: 127.0.0.1
  port: 3306
  dbName: test
  username: root
  password: root
  prefix: proxy_
  charset: utf8mb4
  maxIdleConns: 5
  maxOpenConns: 100
  # Either "silent", "info", "warn", "error", default is "silent"
  level: silent
  # For "postgres" only, either "disable", "require" or "verify-full", default is "disable"
  sslMode: disable
  # For "postgres" only, either "Asia/Shanghai", default is "Asia/Shanghai"
  timeZone: Asia/Shanghai

# logger configuration
log:
  filePath: logs
  fileName: run.log
  # Either "info", "warn", "error", "debug", default is "info"
  level: debug
  # Can be "console" and "file", default is "console"
  # Use comma to separate multiple modes, e.g. "console, file"
  mode: file